用于通过输入的图数据快速计算Cheeger数与稳定因子

In [1]:
# 输入图表格名称

sheet_name = 'gq_test'

In [2]:
import pandas as pd


data = pd.read_excel(sheet_name + '.xlsx',index_col=0)

data

1  2  3  4  5  6  7
1  0  0  1  1  0  0  0
2  0  0  1  0  0  1  0
3  1  1  0  1  0  1  0
4  1  0  1  0  1  0  1
5  0  0  0  1  0  0  1
6  0  1  1  0  0  0  1
7  0  0  0  1  1  1  0

In [3]:
import numpy as np

graph_data = data.values

print(graph_data)

[[0 0 1 1 0 0 0]
 [0 0 1 0 0 1 0]
 [1 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 0 0 1 0 0 1]
 [0 1 1 0 0 0 1]
 [0 0 0 1 1 1 0]]


In [4]:
import networkx as nx

g = nx.from_numpy_array(graph_data)

# 若想打印图需安装 matplotlib 
# conda install matplotlib
# nx.draw(g, with_labels=True)

print(nx.is_connected(g))



True


In [5]:
from itertools import combinations
import math

cheeger_n = 3

node_num = g.number_of_nodes()
nodes = list(range(node_num))


cheeger_list = []

stagnation_point = []

# 对于每阶循环
for i in range(1, cheeger_n+1):

    connect_cnt = 0
    # 对于每种摘除循环
    for comb in combinations(nodes,i):

        #print(comb)

        g_sub = g.copy()
        g_sub.remove_nodes_from(comb)

        if nx.is_connected(g_sub):
            connect_cnt += 1

    cheeger_i = connect_cnt / len(list(combinations(nodes,i)))

    stagnation_point.append(len(list(combinations(nodes,i)))-connect_cnt)
    cheeger_list.append(cheeger_i)
    




print('顶数:'+str(g.number_of_nodes()))
print('边数:'+str(g.number_of_edges()))

for i in range(len(stagnation_point)):
    print('第'+str(i+1)+'阶驻点对数为: '+str(stagnation_point[i]))

# 计算稳定因子

gamma = 0
gamma_f = 0

gamma_list = []

for i in range(len(cheeger_list)):
    print('第'+str(i+1)+'阶Cheeger数为'+str(cheeger_list[i]))
    gamma += cheeger_list[i] / math.factorial(i+1)
    gamma_list.append(gamma)
    gamma_f += 1/math.factorial(i+1)


gamma_n = gamma / gamma_f
gamma_2 = gamma_list[1] / 3.0 * 2
gamma_3 = gamma_list[2] * 0.6

print('2阶稳定因子为:'+str(gamma_2))
print('3阶稳定因子为:'+str(gamma_3))
print('n='+str(cheeger_n)+'阶稳定因子为:'+str(gamma_n))


    


顶数:7
边数:10
第1阶驻点对数为: 0
第2阶驻点对数为: 5
第3阶驻点对数为: 16
第1阶Cheeger数为1.0
第2阶Cheeger数为0.7619047619047619
第3阶Cheeger数为0.5428571428571428
2阶稳定因子为:0.9206349206349206
3阶稳定因子为:0.8828571428571428
n=3阶稳定因子为:0.8828571428571428


上面那一段代码理应可以再封装一下方便读取文件列表速算，但我现在懒得写